language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy3"
before_install:
  - openssl aes-256-cbc -K $encrypted_82809c4caae0_key -iv $encrypted_82809c4caae0_iv -in trackingmore/testdata/testdata.py.enc -out trackingmore/testdata/testdata.py -d
install:
  - pip install requests pytest pytest-cov coveralls
script:
  - py.test --cov-report term-missing --cov=trackingmore
matrix:
  allow_failures:
    - python: 3.7-dev
    - python: pypy3
branches:
  only:
   - master
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - marcoesposito1988@gmail.com
    on_success: always
    on_failure: always
